"""init UserOrm

Revision ID: 9e3c904ed251
Revises: e692bcbb1190
Create Date: 2025-02-06 21:37:03.878265

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e3c904ed251"
down_revision: Union[str, None] = "e692bcbb1190"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("birthday_data", sa.Date(), nullable=True),
        sa.Column("data_create_account", sa.DateTime(), nullable=False),
        sa.Column("hashed_password", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
